### ISSUE TITLE
Adding a CI framework to the project if not used yet - Travis

### ISSUE THREAD

**Issue by nilufer454** [BME-MIT-IET/eng-2020-3-iet-2020#2]
### Update 1
Created .travis.yml

**Comment by BrendaHer** [comment]
Made a job with Travis continued integration service. Requires a rerun

**Comment by BrendaHer** [comment]
Appveyor utilized and built

![Capture](https://user-images.githubusercontent.com/45469500/82150964-4f1cfd80-985a-11ea-9893-dceac961d920.PNG)

**Comment by nilufer454** [comment]
Deleted the Travis CI from the checks with Brenda

**Comment by BrendaHer** [comment]
Deleted the appveyor duplicate webhook with Nil
